excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
 - Zip
 - fastlane
 - .build
 - .swiftpm

disabled_rules:
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - identifier_name
  - nesting
  - todo
  - trailing_whitespace
  - type_name
  - let_var_whitespace
  - prefixed_toplevel_constant
  - switch_case_on_newline

opt_in_rules:
  # Can be auto-corrected
  - anyobject_protocol
  - closure_end_indentation
  - closure_spacing
  - empty_parentheses_with_trailing_closure
  - joined_default_parameter
  - leading_whitespace
  - modifier_order
  - nimble_operator
  - opening_brace
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_type_annotation
  - sorted_imports
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - unused_import
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

  # Can't be auto-corrected
  -  array_init
  -  closure_body_length
  -  collection_alignment
  -  contains_over_filter_count
  -  contains_over_filter_is_empty
  -  contains_over_first_not_nil
  -  discouraged_optional_boolean
  -  discouraged_optional_collection
  -  empty_collection_literal
  -  empty_count
  -  empty_string
  -  empty_xctest_method
  -  extension_access_modifier
  -  fallthrough
  -  fatal_error_message
  -  first_where
  -  force_unwrapping
  -  identical_operands
  -  implicitly_unwrapped_optional
  -  last_where
  -  legacy_multiple
  -  legacy_random
  -  let_var_whitespace
  -  lower_acl_than_parent
  -  multiline_arguments
  -  multiline_function_chains
  -  multiline_literal_brackets
  -  multiline_parameters
  -  object_literal
  -  overridden_super_call
  -  pattern_matching_keywords
  -  prefixed_toplevel_constant
  -  private_action
  -  private_outlet
  -  prohibited_super_call
  -  quick_discouraged_call
  -  quick_discouraged_focused_test
  -  quick_discouraged_pending_test
  -  reduce_into
  -  required_enum_case
  -  single_test_class
  -  sorted_first_last
  -  static_operator
  -  strict_fileprivate
  -  strong_iboutlet
  -  switch_case_on_newline
  -  trailing_closure
  -  unavailable_function
  -  unowned_variable_capture
  -  unused_declaration
  -  vertical_parameter_alignment_on_call
  -  xct_specific_matcher
  -  yoda_condition

line_length:
  warning: 1024
  error: 2048

closure_body_length:
  warning: 60
  error: 80

function_body_length:
  warning: 200
  error: 300

type_body_length:
  warning: 600
  error: 1000

file_length:
  warning: 1000
  error: 1200

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
